// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryEntry } from "./HistoryEntry";

/**
 * history.cursor는 0..entries.length 범위의 undo/redo 위치(STATE-06).
 */
export type HistoryState = { cursor: number, entries: Array<HistoryEntry>, };
