// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryAction } from "./HistoryAction";
import type { ReviewItem } from "./ReviewItem";

/**
 * undo/redo 한 단계(STATE-06). before/after는 해당 시점 item 스냅샷.
 */
export type HistoryEntry = { seq: number, timestamp: string, action: HistoryAction, item_id: string, before: ReviewItem | null, after: ReviewItem | null, 
/**
 * 같은 사용자 동작(예: 전체삭제)으로 묶인 여러 entry를 하나의 undo/redo
 * 단위로 처리하기 위한 그룹 id. 단일 변경은 `None`. 구버전 sidecar 호환을
 * 위해 없으면 `None`으로 역직렬화한다.
 */
group_id?: string, };
