// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PageExclusionMargins } from "./PageExclusionMargins";

/**
 * 한 페이지의 탐지 제외 영역 설정. page_index는 ReviewItem.page와 동일하게
 * 0-indexed(page_dimensions의 1-indexed page_number와는 다른 관례이니 주의).
 */
export type PageExclusionZone = { page_index: number, margins: PageExclusionMargins, };
