// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 페이지 상/하/좌/우에서 각각 얼마나 안쪽까지가 탐지 제외 영역인지(0~1,
 * 페이지 크기에 대한 상대값). 0이면 그 방향은 제외 영역이 없다는 뜻.
 */
export type PageExclusionMargins = { top: number, bottom: number, left: number, right: number, };
