// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FloatingRectState } from "./FloatingRectState";
import type { SidebarDockSide } from "./SidebarDockSide";

/**
 * SIDE-04: 블랙마킹 사이드바만 플로팅+리사이즈를 지원(§6.4).
 */
export type RedactionSidebarViewState = { visible: boolean, dock: SidebarDockSide, floating: boolean, rect: FloatingRectState | null, };
