// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OriginColorScheme } from "./OriginColorScheme";
import type { TextColorPair } from "./TextColorPair";

/**
 * §7.3 색상 설정 전체. focus_border_color는 §7.4 포커스 표시에도 쓰인다.
 */
export type RedactifySettings = { detected: OriginColorScheme, manual: OriginColorScheme, focus_border_color: string, sidebar_selection: TextColorPair, 
/**
 * DET-07: 탐지 제외영역 드래그 가이드선 색상.
 */
exclusion_guide_color: string, };
