// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RelativeBBox } from "./RelativeBBox";
import type { ReviewItemOrigin } from "./ReviewItemOrigin";
import type { ValidationStatus } from "./ValidationStatus";

/**
 * 블랙마킹 목록의 한 행(§5.2). category는 §5.3의 검출 구분값 또는 사용자
 * 지정("Custom") 문자열 — 실제 드롭다운 값 집합은 DET-02/LIST-03에서 다룬다.
 */
export type ReviewItem = { id: string, origin: ReviewItemOrigin, page: number, bbox: RelativeBBox, 
/**
 * 수정 전 bbox(수정 시 보존). 없으면 None.
 */
original_bbox: RelativeBBox | null, category: string, content: string, 
/**
 * 검출 규칙 id. detected 항목에만 존재, manual/imported는 None.
 */
pattern_type: string | null, 
/**
 * 0~1. detected 항목에만 존재.
 */
confidence: number | null, validation: ValidationStatus, modified: boolean, created_at: string, updated_at: string, };
