// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarDockSide } from "./SidebarDockSide";

export type SidebarViewState = { visible: boolean, dock: SidebarDockSide, };
