// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HistoryState } from "./HistoryState";
import type { PageExclusionZone } from "./PageExclusionZone";
import type { ReviewItem } from "./ReviewItem";
import type { SidecarPageDimensions } from "./SidecarPageDimensions";
import type { SourceInfo } from "./SourceInfo";
import type { ViewState } from "./ViewState";

export type SidecarDocument = { schema_version: number, app: string, source: SourceInfo, view_state: ViewState, page_dimensions: Array<SidecarPageDimensions>, review_items: Array<ReviewItem>, history: HistoryState, 
/**
 * DET-07(§6.3.1 신규): 페이지별 자동검출 제외 영역(헤더/푸터 등 여백).
 * 이 필드가 없는 구버전 sidecar 파일도 그대로 열 수 있도록
 * `#[serde(default)]`로 빈 벡터를 기본값으로 둔다(이 코드베이스에서
 * 처음 쓰는 하위호환 처리 — `deserializes_old_sidecar_without_exclusion_zones_field`
 * 테스트로 명시적으로 검증함).
 */
exclusion_zones: Array<PageExclusionZone>, };
