// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 파일 동일성 판정(§4.4)에 쓰이는 원문 정보. 경로/파일명은 참고용일 뿐,
 * 판정은 page_count + page_dimensions + text_fingerprint로 한다.
 */
export type SourceInfo = { filename: string, path: string, page_count: number, text_fingerprint: string, 
/**
 * ISO 8601(RFC3339) 문자열. 프론트의 `Date.toISOString()`과 동일한 형식.
 */
created_at: string, updated_at: string, };
