// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 텍스트가 실제로 보이는 UI(목록 행)의 배경·폰트색.
 */
export type TextColorPair = { background: string, font: string, };
