// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §5.3 검증 결과. 변형 이름을 그대로 직렬화하므로(별도 rename 없음) 스펙의
 * "Valid"/"Invalid"/"ChecksumNotApplicable"/"NotValidated"와 정확히 일치한다.
 */
export type ValidationStatus = "Valid" | "Invalid" | "ChecksumNotApplicable" | "NotValidated";
