// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * §5.4 Excel 스키마 한 행. `$`가 붙은 컬럼(filename, bbox)은 사이드바 UI에는
 * 안 보이지만 파일에는 그대로 유지된다.
 */
export type XlsxRow = { filename: string, category: string, content: string, page: number, bbox: string, updated_at: string, };
